import {ITEMS,BANDS,ROUTES,EVENTS,WORLD,createState,capacity,pack,lock,score,drain,damage,enterEvent,useItem,shortcut,eventSequence,breakdown,speedFactor,canMove} from './engine.js';
import {scenic,drawWorld} from './scene.js';
const $=(q)=>document.querySelector(q),app=$('#app');
const stored=(key,fallback)=>{try{const v=localStorage.getItem(key);return v===null?fallback:JSON.parse(v);}catch{return fallback;}};
const prefs={band:Math.max(0,Math.min(5,Math.floor(Number(stored('sunstone.band',0))||0))),volume:Math.max(0,Math.min(1,Number(stored('sunstone.volume',.35))||0)),muted:!!stored('sunstone.muted',false),reduced:!!stored('sunstone.reduced',matchMedia('(prefers-reduced-motion: reduce)').matches)};
function savePrefs(){for(const [k,v]of Object.entries(prefs))try{localStorage.setItem('sunstone.'+k,JSON.stringify(v));}catch{}document.body.classList.toggle('reduced',prefs.reduced);}
let mode='loading',s=null,g=null,storyId=0,beat=1,walkthrough=0,last=0,paintLast=0,sceneTime=0,canvas=null,ctx=null,roundElapsed=0,roundStart=0,eventList=[],eventIndex=0,section=0,result=null,key={},drag=null;
let audio=null,musicTimer=null,musicStep=0,mood='menu';
function audioStart(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});if(!musicTimer)musicTimer=setInterval(music,450);}catch{}}
function tone(freq,duration=.14,type='sine',gain=.11){if(!audio||prefs.muted||prefs.volume===0)return;try{const osc=audio.createOscillator(),amp=audio.createGain();osc.type=type;osc.frequency.value=freq;amp.gain.setValueAtTime(0,audio.currentTime);amp.gain.linearRampToValueAtTime(gain*prefs.volume,audio.currentTime+.012);amp.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(amp);amp.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}catch{}}
function music(){if(document.hidden)return;const notes={menu:[261.63,329.63,392,523.25],pack:[293.66,369.99,440,369.99],travel:[329.63,392,493.88,392],events:[220,261.63,329.63,246.94],end:[261.63,329.63,392,523.25,659.25,523.25]};const arr=notes[mood]||notes.menu;tone(arr[musicStep++%arr.length],.4,'sine',.035);}
function sfx(kind='pick'){const tones={pick:587,lock:220,route:440,event:196,arrival:784};tone(tones[kind]||587,.22,'triangle',.14);}
function esc(text){return String(text).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function time(seconds){const n=Math.floor(seconds);return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
function bandOptions(){return BANDS.map((b,i)=>`<option value="${i}" ${i===prefs.band?'selected':''}>Grades ${b.name}</option>`).join('');}
function header(){return `<header class="topbar"><div class="brand"><img src="./assets/lighthouse.svg" alt=""><div><strong>DECIPHER ACADEMY</strong><span>SKILL CHALLENGE FRIDAY</span></div></div><div class="top-actions"><button class="sound-btn" id="sound" aria-label="Sound settings" aria-expanded="false">${prefs.muted?'♪ Off':'♪ Sound'}</button></div></header>`;}
function shell(content){canvas=null;ctx=null;app.innerHTML=`<div class="shell">${header()}${content}</div>`;$('#sound').onclick=()=>soundPanel();document.body.classList.toggle('reduced',prefs.reduced);}
function soundPanel(){const old=$('.sound-panel');if(old){old.remove();$('#sound').setAttribute('aria-expanded','false');return;}$('#sound').setAttribute('aria-expanded','true');const p=document.createElement('div');p.className='sound-panel';p.innerHTML=`<button id="mute">${prefs.muted?'Turn sound on':'Mute sound'}</button><label for="volume">Volume</label><input id="volume" type="range" min="0" max="100" value="${prefs.volume*100}"><button class="ghost" id="soundClose">Done</button>`;$('.shell').append(p);$('#mute').onclick=()=>{audioStart();prefs.muted=!prefs.muted;savePrefs();$('#sound').textContent=prefs.muted?'♪ Off':'♪ Sound';$('#mute').textContent=prefs.muted?'Turn sound on':'Mute sound';};$('#volume').oninput=e=>{audioStart();prefs.volume=Number(e.target.value)/100;savePrefs();};$('#soundClose').onclick=()=>soundPanel();}
function bindCanvas(){canvas=$('canvas');ctx=canvas?.getContext('2d');resize();}
function resize(){if(!canvas)return;const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}
window.addEventListener('resize',resize);
function announce(msg){$('#announcer').textContent=msg;}
function note(msg){const el=$('#travelNote')||$('#packNote');if(el)el.textContent=msg;announce(msg);}
function menu(){mode='menu';mood='menu';s=null;g=null;key={};storyId++;shell(`<section class="menu"><canvas class="backdrop" aria-hidden="true"></canvas><div class="island-tag">Sunstone Island</div><div class="menu-copy"><p class="eyebrow">A SKILL CHALLENGE FRIDAY ADVENTURE</p><h1>Play your<br>hand.<em>Survive the Island</em></h1><p>One island. One backpack.<br>A whole adventure of choices.</p><label class="menu-select" for="menuBand">Your expedition<select id="menuBand">${bandOptions()}</select></label><button class="primary play" id="play">Let’s play &nbsp; →</button><div class="menu-links"><button id="how">How to play</button><button id="credits">Credits</button></div><div class="menu-foot"><label><input id="reduced" type="checkbox" ${prefs.reduced?'checked':''}> Reduce motion</label></div></div></section>`);bindCanvas();$('#menuBand').onchange=e=>{prefs.band=+e.target.value;savePrefs();};$('#play').onclick=()=>{audioStart();setup();};$('#how').onclick=()=>{walkthrough=0;how();};$('#credits').onclick=credits;$('#reduced').onchange=e=>{prefs.reduced=e.target.checked;savePrefs();};}
function setup(){mode='setup';shell(`<section class="panel-wrap"><form class="panel" id="setup"><p class="eyebrow">YOUR EXPEDITION</p><h2>Meet our explorer.</h2><p class="muted">Your name goes on your Lighthouse result card.</p><label for="studentName">Your name</label><input id="studentName" type="text" required maxlength="60" placeholder="Enter your name" autocomplete="off"><label for="setupBand">Grade band</label><select id="setupBand">${bandOptions()}</select><div class="row"><button type="button" class="ghost" id="back">Back</button><button class="primary" type="submit">Play Now →</button></div></form></section>`);$('#back').onclick=menu;$('#setup').onsubmit=e=>{e.preventDefault();const name=$('#studentName').value.trim();if(!name){$('#studentName').setCustomValidity('Please enter your name.');$('#studentName').reportValidity();return;}prefs.band=+$('#setupBand').value;savePrefs();s=createState(prefs.band,name);audioStart();story();};$('#studentName').oninput=e=>e.target.setCustomValidity('');$('#studentName').focus();}
function how(){mode='how';const steps=[['🎒','Pack','Tap or drag supplies into your backpack. Lock it when you’re ready.'],['🧭','Navigate','Tap the path, use the arrow keys, or hold the movement buttons.'],['⛈️','Adapt','Use a supply near an obstacle, or walk another path to the Lighthouse.']];const step=steps[walkthrough];shell(`<section class="panel-wrap"><div class="panel" id="howPanel"><p class="eyebrow">HOW TO PLAY · ${walkthrough+1} / 3</p><div class="instructions"><span class="big-icon" aria-hidden="true">${step[0]}</span><h2>${step[1]}</h2><p>${step[2]}</p></div><div class="steps">${steps.map((_,i)=>`<i class="step-dot ${i===walkthrough?'active':''}"></i>`).join('')}</div><div class="row"><button class="ghost" id="howBack">${walkthrough?'Previous':'Main Menu'}</button><button class="primary" id="howNext">${walkthrough===2?'Ready!':'Next →'}</button></div></div></section>`);$('#howBack').onclick=()=>{if(walkthrough){walkthrough--;how();}else menu();};$('#howNext').onclick=()=>{if(walkthrough<2){walkthrough++;how();}else menu();};let start=0;$('#howPanel').ontouchstart=e=>start=e.changedTouches[0].clientX;$('#howPanel').ontouchend=e=>{const d=e.changedTouches[0].clientX-start;if(Math.abs(d)>65){walkthrough=Math.max(0,Math.min(2,walkthrough+(d<0?1:-1)));how();}};}
function credits(){mode='credits';shell(`<section class="panel-wrap"><div class="panel"><p class="eyebrow">THE PEOPLE & THE ISLAND</p><h2>Made for curious minds.</h2><p>Play Your Hand: Survive the Island<br>Decipher Academy · Skill Challenge Friday</p><p style="margin-top:18px">Original lightweight placeholder scenery and synthesized music and sound effects. No third-party audio or music is used.</p><div class="row"><button class="primary" id="back">Main Menu</button></div></div></section>`);$('#back').onclick=menu;}
const storyLines=[
 ['The boat rocks gently as it approaches a bright, unfamiliar island.','In the distance, a tall Lighthouse stands on a hill, shining across the water.'],
 ['Suddenly, the engine gives out. The boat can go no farther.','Welcome to Sunstone Island.'],
 ['The good news? The Lighthouse is visible.','The bad news? You have to get there on foot—and you can’t carry everything.'],
 ['Around the shore are supplies that could help you on the journey.','Your backpack has limited space, so every choice matters.','A rope could save you later. A compass could reveal a shortcut. Extra food could keep your energy up.','But if you fill your bag too early, you may leave something important behind.'],
 ['And the island won’t stay the same.','Paths can change, weather can turn, and unexpected obstacles can appear.'],
 ['Your mission is simple: reach the Lighthouse before sunset.','The real challenge? Playing your hand wisely.']
];
async function story(){mode='story';beat=1;const id=++storyId;shell(`<section class="story"><canvas aria-label="Animated journey to Sunstone Island"></canvas><button class="skip" id="skip">Skip story →</button><div class="narrative"><span class="beat-tag" id="beatTag"></span><div id="lines"></div></div></section>`);bindCanvas();$('#skip').onclick=()=>{storyId++;packScreen();};for(let i=0;i<storyLines.length;i++){if(id!==storyId)return;beat=i+1;sceneTime=0;$('#beatTag').textContent=`SUNSTONE ISLAND · ${beat} / 6`;$('#lines').innerHTML='';const sceneAnimation=canvas.animate(prefs.reduced?[{opacity:.85},{opacity:1}]:[{transform:'scale(1.02) translateX(-1%)'},{transform:'scale(1.05) translateX(0)'}],{duration:storyLines[i].join(' ').length*36+1600,fill:'forwards',easing:'ease-out'});for(const line of storyLines[i]){if(id!==storyId)return;const p=document.createElement('p');p.textContent=line;$('#lines').append(p);const animation=p.animate([{opacity:0,transform:prefs.reduced?'none':'translateY(8px)',offset:0},{opacity:1,transform:'none',offset:.15},{opacity:1,transform:'none',offset:1}],{duration:Math.max(1800,line.length*36),fill:'both'});await animation.finished.catch(()=>{});}await sceneAnimation.finished.catch(()=>{});}if(id===storyId)packScreen();}
function packScreen(){mode='pack';mood='pack';s.round=1;roundElapsed=0;roundStart=s.elapsed;shell(`<div class="page-head"><div><span class="round-pill">ROUND 1 / 3 · BASE CAMP</span><h2>Pack for survival.</h2><p class="muted">Tap or drag to pack. Tap again to put it back.</p></div><div class="timer"><strong id="timer">${time(BANDS[s.band].times[0])}</strong><span id="timerLabel">packing target</span></div></div><section class="pack-layout"><div class="supplies" id="supplies"></div><aside class="backpack" id="backpack"><img src="./assets/pack.svg" alt=""><h3>Your backpack</h3><div class="slots" id="slots"></div><p id="capacity"></p><div class="pack-list" id="packList"></div><button class="primary" id="review">Review & lock →</button><p class="muted">Once locked, you can use supplies, but you can’t swap or drop them.</p></aside></section><p class="note sr-only" id="packNote" role="status"></p>`);renderPack();$('#review').onclick=review;}
function renderPack(){if(mode!=='pack')return;const b=BANDS[s.band];$('#supplies').innerHTML=ITEMS.slice(0,b.pool).map(i=>`<button class="item ${s.inventory.includes(i.id)?'packed':''}" data-item="${i.id}" aria-pressed="${s.inventory.includes(i.id)}" aria-label="${i.name}, ${i.slots} slots. ${i.effect}"><span class="emoji" aria-hidden="true">${i.icon}</span><span class="slot">${i.slots} ${i.slots===1?'slot':'slots'}</span><strong>${i.name}</strong><small>${i.effect}</small></button>`).join('');const n=capacity(s);$('#slots').innerHTML=Array.from({length:b.capacity},(_,i)=>`<i class="${i<n?'filled':''}"></i>`).join('');$('#capacity').textContent=`${n} / ${b.capacity} slots filled`;$('#packList').textContent=s.inventory.length?s.inventory.map(id=>ITEMS.find(i=>i.id===id).name).join(' · '):'What will you take on your journey?';document.querySelectorAll('[data-item]').forEach(el=>{el.onclick=()=>togglePack(el.dataset.item);el.onpointerdown=e=>{if(e.button!==0)return;drag={id:el.dataset.item,x:e.clientX,y:e.clientY,moved:false,el,pointer:e.pointerId};};});}
function togglePack(id){if(pack(s,id)){sfx();renderPack();}else{note('Your backpack is full. Put something back to make room.');$('#capacity').textContent='Not enough room — tap a packed item to remove it.';}}
window.addEventListener('pointermove',e=>{if(!drag||mode!=='pack')return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>10&&!drag.moved){drag.moved=true;drag.el.setPointerCapture?.(drag.pointer);const ghost=document.createElement('div');ghost.className='drag-ghost';ghost.textContent=ITEMS.find(i=>i.id===drag.id).icon;document.body.append(ghost);}if(drag.moved){const ghost=$('.drag-ghost');ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';$('#backpack').classList.add('drag-over');}});
window.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;if(d.moved){e.preventDefault();d.el.onclick=null;const r=$('#backpack')?.getBoundingClientRect();if(r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom&&!s.inventory.includes(d.id))togglePack(d.id);$('.drag-ghost')?.remove();$('#backpack')?.classList.remove('drag-over');renderPack();}},true);
window.addEventListener('pointercancel',()=>{drag=null;$('.drag-ghost')?.remove();$('#backpack')?.classList.remove('drag-over');key={};});
function review(){const d=document.createElement('dialog');d.innerHTML=`<h2>Review your pack</h2><p>${s.inventory.length?s.inventory.map(id=>esc(ITEMS.find(i=>i.id===id).name)).join(' · '):'Your backpack is empty. You can still take the longer paths.'}</p><p><strong>${capacity(s)} / ${BANDS[s.band].capacity} slots</strong><br>This lock is one-way. Ready to set off?</p><div class="row"><button class="ghost" id="goBack">Go Back</button><button class="primary" id="confirmLock">Confirm</button></div>`;app.append(d);d.showModal();$('#goBack').onclick=()=>d.remove();$('#confirmLock').onclick=()=>{lock(s);sfx('lock');d.remove();transition(1);};d.addEventListener('cancel',()=>d.remove());}
function transition(round){mode='transition';key={};shell(`<section class="panel-wrap transition"><div class="panel"><div class="big-icon">${round===1?'🎒':'🏝️'}</div><p class="eyebrow">ROUND ${round} COMPLETE</p><h2>${round===1?'Backpack locked.':'Across the island.'}</h2><p class="muted">${round===1?'Your choices are coming with you.':'The Lighthouse is closer. The island is changing.'}</p><div class="recap">${s.inventory.map(id=>{const i=ITEMS.find(i=>i.id===id);return `<span>${i.icon} ${i.name}</span>`;}).join('')||'<span>Empty backpack · find your own way</span>'}</div><button class="primary" id="continue">${round===1?'Cross the island →':'See what lies ahead →'}</button></div></section>`);$('#continue').onclick=()=>{if(round===1){s.round=2;section=0;roundStart=s.elapsed;startTravel(true);}else{s.round=3;roundStart=s.elapsed;eventList=eventSequence(s);s.routeChangesTarget=BANDS[s.band].changes[0]+(eventList.length>BANDS[s.band].events[0]?BANDS[s.band].changes[1]-BANDS[s.band].changes[0]:0);eventIndex=0;startTravel();}};}
function startTravel(fork=false){mode='travel';mood=s.round===2?'travel':'events';key={};roundElapsed=s.elapsed-roundStart;const event=fork?null:s.round===2?ROUTES[s.route].event:eventList[eventIndex];const changes=s.round===3?Math.min(eventIndex,s.routeChangesTarget||0):0;g={detourY:changes%2?515:150,routeChanges:changes,...WORLD.start,fork,routes:ROUTES,event,blocked:!!event&&!['storm','injury'].includes(event),opened:false,moving:false,target:null,path:[],checkpoint:{...WORLD.start},tokens:[{x:240,y:310,collected:false},{x:690,y:320,collected:false}],shortcutAvailable:s.round===2&&section===1,final:s.round===3&&eventIndex===eventList.length-1,compass:false,sheltered:false,campFire:false,efficient:false,detoured:false,delayedApplied:false};if(!fork){const rescued=enterEvent(s,event);if(rescued)g.rescueMessage=true;sfx('event');}renderTravel();if(g.rescueMessage)note('Rescued to a safe checkpoint. +20 seconds, −75 points. You can keep going.');else if(event==='injury')note('You hurt your ankle: −50 Health. First aid helps, or keep moving carefully.');else if(s.round===3&&s.band>=4&&s.delayedDrain>0){const debt=s.delayedDrain;s.delayedDrain=0;drain(s,debt);note('The earlier detour catches up with you: your energy reserve is lower.');}else if(event)note(EVENTS[event].hint);}
function renderTravel(){shell(`<div class="travel-head"><div class="travel-title"><span class="round-pill">ROUND ${s.round} / 3 · ${s.round===2?'CROSS THE ISLAND':'THE ISLAND CHANGES'}</span><h2>${g.fork?'Choose your path.':s.round===2?ROUTES[s.route].name+' trail':EVENTS[g.event].name}</h2></div><div class="meters"><div class="meter"><label for="energy">Energy <span id="energyValue"></span></label><progress id="energy" max="100" value="100"></progress></div><div class="meter health"><label for="health">Health <span id="healthValue"></span></label><progress id="health" max="100" value="100"></progress></div></div><div class="timer"><strong id="timer"></strong><span id="timerLabel"></span></div></div><div class="world-wrap"><canvas id="world" tabindex="0" aria-label="Island path. Use arrow keys or movement buttons. Tap a sign to walk a route, collect gold tokens, and use supplies near obstacles."></canvas><div class="world-banner" id="worldBanner">${g.fork?'Walk to a wooden sign to choose your route.':s.round===2?`Trail ${section+1} / 3 · Walk to the right-hand sign`:`Event ${eventIndex+1} / ${eventList.length}${g.routeChanges?' · Path shift '+g.routeChanges:''} · ${g.final?'Reach the Lighthouse':'Follow the onward sign'}`}</div></div><div class="inventory-bar" id="inventory" aria-label="Locked backpack"></div><div class="controls"><div class="control-copy"><p id="travelNote" role="status"></p><p>Tap to walk · arrow keys / WASD · hold the buttons</p><div class="route-help" id="routeHelp"></div></div><div class="dpad" aria-label="Movement controls"><button data-dir="ArrowUp" aria-label="Move up">▲</button><button data-dir="ArrowLeft" aria-label="Move left">◀</button><button data-dir="ArrowDown" aria-label="Move down">▼</button><button data-dir="ArrowRight" aria-label="Move right">▶</button></div></div>`);bindCanvas();renderInventory();renderRouteHelp();updateHUD();canvas.onpointerdown=e=>{audioStart();const r=canvas.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*1000,y=(e.clientY-r.top)/r.height*600;if(g.fork){if(x>430){const i=[120,240,380,500].reduce((best,v,j)=>Math.abs(v-y)<Math.abs([120,240,380,500][best]-y)?j:best,0);chooseRoute(Object.keys(ROUTES)[i]);}else setTarget(x,y);return;}if(Math.hypot(x-330,y-(g.detourY===515?480:115))<100){detour();return;}if(g.shortcutAvailable&&Math.hypot(x-720,y-485)<90){goShortcut();return;}setTarget(x,y);};document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);key[b.dataset.dir]=true;g.target=null;g.path=[];};b.onpointerup=b.onpointercancel=()=>key[b.dataset.dir]=false;b.onlostpointercapture=()=>key[b.dataset.dir]=false;});}
function renderInventory(){if(!$('#inventory'))return;$('#inventory').innerHTML=s.inventory.map(id=>{const i=ITEMS.find(i=>i.id===id);return `<button data-use="${id}" class="${s.activeGear.has(id)?'active':''}" title="${i.effect}"><span class="emoji" aria-hidden="true">${i.icon}</span>${i.name}${s.activeGear.has(id)?' ✓':''}</button>`;}).join('')||'<p class="muted">🎒 Backpack empty · the land paths are still open.</p>';document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>activate(b.dataset.use));}
function renderRouteHelp(){const h=$('#routeHelp');if(g.fork){h.innerHTML=Object.entries(ROUTES).map(([id,r])=>`<button data-route="${id}">${r.name} →</button>`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>chooseRoute(b.dataset.route));}else{h.innerHTML=`<button id="detour">${EVENTS[g.event].detour} ↗</button><button id="onward">Onward →</button>${g.shortcutAvailable?'<button id="risk">Risky shortcut ↗</button>':''}`;$('#detour').onclick=detour;$('#onward').onclick=()=>{if(g.blocked&&g.x<535){setTarget(370,350);note('Walk around the obstacle, or use a helpful supply nearby.');}else{g.path=[{x:690,y:350},{x:930,y:350}];nextTarget();}};if($('#risk'))$('#risk').onclick=goShortcut;}}
function setTarget(x,y){g.path=[];g.target={x:Math.max(40,Math.min(960,x)),y:Math.max(85,Math.min(530,y))};}
function nextTarget(){g.target=g.path.shift()||null;}
function chooseRoute(id){const i=Object.keys(ROUTES).indexOf(id);g.pendingRoute=id;g.path=[{x:280,y:350},{x:620,y:[120,240,380,500][i]}];nextTarget();note(`Walking toward the ${ROUTES[id].name} trail…`);}
function detour(){if(g.fork)return;g.detoured=true;g.path=g.x>560?[{x:635,y:350},{x:930,y:350}]:[{x:335,y:350},{x:335,y:g.detourY},{x:620,y:g.detourY},{x:635,y:350},{x:930,y:350}];nextTarget();note(g.event==='storm'?'Walk under the shelter, then continue.':'Follow the open land path. You can always keep going.');}
function goShortcut(){if(!g.shortcutAvailable)return;g.path=g.x<535&&g.blocked?[{x:335,y:150},{x:620,y:150},{x:640,y:350},{x:720,y:485}]:[{x:650,y:350},{x:720,y:485}];nextTarget();note('Walk to the risky shortcut. 50% success, or 90% with this route’s equipment.');}
function activate(id){if(mode!=='travel')return;let context=null;const consumable=['water','food','aid'].includes(id);if(id==='matches'&&g.event==='storm'&&Math.hypot(g.x-297,g.y-460)<95)context='camp';else if(id==='compass'&&!g.fork)context=g.event;else if(id==='shoes'&&!g.fork)context=g.event;else if(!g.fork&&(Math.hypot(g.x-440,g.y-350)<180||['storm','injury'].includes(g.event)))context=g.event;const r=useItem(s,id,context);if(!r.ok){note(r.repeat?'Already used here. Save your next action for another obstacle.':'That supply is no longer in your pack.');return;}if(r.good){if(r.opens){g.blocked=false;g.opened=true;if(!g.efficient){score(s,'adaptation',50,'Obstacle completed efficiently');g.efficient=true;}note('A clever use of supplies! The way is clear.');}else note(`${ITEMS.find(i=>i.id===id).name} helped. +20 Resource Efficiency`);if(id==='compass'){g.compass=true;g.path=g.x>560?[{x:930,y:350}]:[{x:310,y:350},{x:375,y:205},{x:560,y:205},{x:640,y:350},{x:930,y:350}];nextTarget();}if(id==='matches'){g.campFire=true;g.sheltered=true;}}else note('That supply wasn’t needed here. −30 points for unnecessary use.');sfx();renderInventory();updateHUD();}
function updateHUD(){if(!s)return;if($('#energy')){$('#energy').value=s.energy;$('#energyValue').textContent=Math.ceil(s.energy);$('#health').value=s.health;$('#healthValue').textContent=Math.ceil(s.health);}if($('#timer')){const elapsed=mode==='pack'?s.elapsed:s.elapsed-roundStart;const target=BANDS[s.band].times[s.round-1];const over=elapsed>target;$('#timer').textContent=over?`+${time(elapsed-target)}`:time(target-elapsed);$('#timerLabel').textContent=over?'Keep going · soft target':mode==='pack'?'packing target':'round target';}}
function step(dt){if(mode!=='travel'||!g)return;let dx=0,dy=0;const keyboard=key.ArrowLeft||key.ArrowRight||key.ArrowUp||key.ArrowDown||key.a||key.d||key.w||key.s;if(keyboard){g.target=null;g.path=[];dx=(key.ArrowRight||key.d?1:0)-(key.ArrowLeft||key.a?1:0);dy=(key.ArrowDown||key.s?1:0)-(key.ArrowUp||key.w?1:0);}else if(g.target){dx=g.target.x-g.x;dy=g.target.y-g.y;const distance=Math.hypot(dx,dy);if(distance<4){g.x=g.target.x;g.y=g.target.y;nextTarget();dx=0;dy=0;}}
const dist=Math.hypot(dx,dy);g.moving=dist>0;if(dist>0){const base=s.round===2?(g.fork?105:2520/BANDS[s.band].times[1]/ROUTES[s.route].length):850*eventList.length/BANDS[s.band].times[2];let speed=base*speedFactor(s);const rough=['tree','bridge'].includes(g.event);if(rough&&!s.activeGear.has('shoes'))speed*=.85;if(g.event==='storm'&&!g.sheltered&&!s.activeGear.has('jacket')&&!s.activeGear.has('blanket'))speed*=.8;const amount=Math.min(dist,speed*dt);const nx=g.x+dx/dist*amount,ny=g.y+dy/dist*amount;let moved=0;if(canMove(nx,ny,g.blocked)){moved=Math.hypot(nx-g.x,ny-g.y);g.x=nx;g.y=ny;}else{if(canMove(nx,g.y,g.blocked)){moved+=Math.abs(nx-g.x);g.x=nx;}if(canMove(g.x,ny,g.blocked)){moved+=Math.abs(ny-g.y);g.y=ny;}if(!moved&&!keyboard){g.target=null;g.path=[];note('The direct path is blocked. Use a supply nearby, or follow the land path.');}}
if(!g.fork){if(g.y<230&&g.x>330&&g.x<625)g.detoured=true;let spent=moved*(s.round===2?50/2520:28/(850*eventList.length));if(rough&&!s.activeGear.has('shoes'))spent*=1.12;if(g.event==='storm'&&!g.sheltered&&!s.activeGear.has('jacket')&&!s.activeGear.has('blanket'))spent*=2;if(s.band>=4&&s.round===2&&g.detoured&&g.y<230){s.delayedDrain+=spent*.45;spent*=.55;}const energyBefore=s.energy;drain(s,spent);if(energyBefore>0&&s.energy===0)note('Energy is empty. Move at half speed and keep going. −100 points.');}}
if(g.fork&&g.x>=600){const positions=[120,240,380,500];const at=positions.findIndex(y=>Math.abs(g.y-y)<25);if(at<0)return;s.route=Object.keys(ROUTES)[at];sfx('route');startTravel();return;}if(g.fork)return;
if(g.x>585)g.checkpoint={x:620,y:350};
if(g.event==='storm'&&Math.abs(g.y-g.detourY)<40&&g.x>440&&g.x<590&&!g.sheltered){g.sheltered=true;note('The shelter protects you from the storm.');if(!g.efficient){score(s,'adaptation',50,'Found storm shelter');g.efficient=true;}}
for(const tok of g.tokens){if(!tok.collected&&Math.hypot(tok.x-g.x,tok.y-g.y)<27){tok.collected=true;score(s,'adaptation',25,'Optional token');sfx();note('Island token collected. +25 Adaptation');}}
if(g.shortcutAvailable&&Math.hypot(g.x-720,g.y-485)<30){g.shortcutAvailable=false;const before=s.rescues;if(shortcut(s)){g.x=860;g.y=350;note('You made the shortcut! +75 Adaptation');}else{g.x=g.checkpoint.x;g.y=g.checkpoint.y;note(s.rescues>before?'Rescued to a checkpoint. +20 seconds, −75 points.':'The shortcut gave way. −25 Health. The main path is still open.');}g.target=null;g.path=[];renderRouteHelp();}
if(g.x>=916&&Math.abs(g.y-350)<55){if(s.round===2){section++;if(section===3){score(s,'progress',300,'Route completed');transition(2);}else startTravel();}else{eventIndex++;if(eventIndex===eventList.length){score(s,'progress',300,'Reached the Lighthouse');finish();}else startTravel();}}
}
function finish(){mode='end';mood='end';key={};sfx('arrival');result=breakdown(s);shell(`<section class="end-wrap"><article class="result-card" id="resultCard"><div class="result-top"><img src="./assets/lighthouse.svg" alt=""><p class="eyebrow">DECIPHER ACADEMY<br>SKILL CHALLENGE FRIDAY</p></div><h2>YOU MADE IT TO THE LIGHTHOUSE!</h2><p class="student">${esc(s.name)}</p><p class="grade">Grades ${BANDS[s.band].name} · ${ROUTES[s.route].name} route</p><div class="score-lines">${[['Island Progress',result.progress],['Resource Efficiency',result.resource],['Adaptation',result.adaptation],['Time Bonus',result.timeBonus],['Penalties','−'+result.penalties]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><div class="final-score"><span>FINAL<br>STRATEGY SCORE</span><strong>${result.total}</strong></div><p class="completion">Completion time <strong>${time(result.seconds)}</strong></p></article><div class="row end-actions"><button class="dark" id="download">↓ Download card</button><button class="dark" id="share" hidden>Share card ↗</button><button class="ghost" id="again">Play Again</button><button class="ghost" id="mainMenu">Main Menu</button></div><p class="muted" id="shareStatus" role="status">Share your card in your class WhatsApp group.</p></section>`);$('#download').onclick=downloadCard;$('#again').onclick=$('#mainMenu').onclick=menu;prepareShare();}
function cardCanvas(){const c=document.createElement('canvas');c.width=900;c.height=1120;const x=c.getContext('2d');x.fillStyle='#e5ce92';x.fillRect(0,0,900,1120);x.fillStyle='#fff9e9';x.beginPath();x.roundRect(38,38,824,1044,34);x.fill();x.textAlign='center';x.fillStyle='#1e5942';x.font='bold 22px sans-serif';x.fillText('DECIPHER ACADEMY',450,105);x.font='16px sans-serif';x.fillText('SKILL CHALLENGE FRIDAY',450,135);x.drawImage(assets[0],397,163,106,106);x.font='bold 29px Georgia';x.fillText('YOU MADE IT TO THE LIGHTHOUSE!',450,320);let size=40;do{x.font=`bold ${size--}px sans-serif`;}while(x.measureText(s.name).width>720&&size>15);x.fillText(s.name,450,387);x.font='23px sans-serif';x.fillStyle='#5f7055';x.fillText(`Grades ${BANDS[s.band].name} · ${ROUTES[s.route].name} route`,450,431);const rows=[['Island Progress',result.progress],['Resource Efficiency',result.resource],['Adaptation',result.adaptation],['Time Bonus',result.timeBonus],['Penalties','−'+result.penalties]];rows.forEach(([label,value],i)=>{const y=514+i*60;x.textAlign='left';x.fillStyle='#254637';x.font='25px sans-serif';x.fillText(label,98,y);x.textAlign='right';x.font='bold 27px sans-serif';x.fillText(String(value),802,y);});x.fillStyle='#1e5942';x.beginPath();x.roundRect(80,816,740,139,20);x.fill();x.fillStyle='#fff1c5';x.textAlign='left';x.font='20px sans-serif';x.fillText('FINAL STRATEGY SCORE',109,876);x.textAlign='right';x.font='bold 70px Georgia';x.fillText(String(result.total),785,910);x.textAlign='center';x.fillStyle='#254637';x.font='24px sans-serif';x.fillText(`Completion time  ${time(result.seconds)}`,450,1018);return c;}
function pngBlob(){return new Promise((resolve,reject)=>cardCanvas().toBlob(b=>b?resolve(b):reject(new Error('PNG could not be created')),'image/png'));}
async function downloadCard(){try{const blob=await pngBlob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Sunstone-Island-Result.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#shareStatus').textContent='Card downloaded. Share it with your class when you’re ready.';}catch{$('#shareStatus').textContent='Download is unavailable here. Screenshot the complete card above.';}}
async function prepareShare(){try{const blob=await pngBlob();const file=new File([blob],'Sunstone-Island-Result.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})&&$('#share')){$('#share').hidden=false;$('#share').onclick=async()=>{try{await navigator.share({files:[file],title:'My Sunstone Island result'});}catch(e){if(e.name!=='AbortError')$('#shareStatus').textContent='Use Download to save and share your card.';}};}}catch{}}
window.addEventListener('keydown',e=>{if(mode!=='travel'||e.target.matches('input,select,textarea'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();key[e.key]=true;}});window.addEventListener('keyup',e=>{key[e.key]=false;});window.addEventListener('blur',()=>key={});
function frame(now){const wallDt=(now-last)/1000||0,dt=Math.min(.05,wallDt);last=now;if(!document.hidden){sceneTime+=dt;if(mode==='pack'||mode==='travel'){s.elapsed+=wallDt;step(dt);updateHUD();}if(canvas&&ctx&&now-paintLast>32){paintLast=now;ctx.clearRect(0,0,canvas.width,canvas.height);if(mode==='menu'||mode==='story')scenic(ctx,canvas.width,canvas.height,sceneTime,mode==='menu'?3:beat,prefs.reduced);if(mode==='travel')drawWorld(ctx,canvas.width,canvas.height,g,s,sceneTime,prefs.reduced);}}requestAnimationFrame(frame);}
const assets=[];
async function preload(){const paths=['./assets/lighthouse.svg','./assets/boat.svg','./assets/pack.svg'];const slow=setTimeout(()=>{if(mode==='loading')$('#loadnote').textContent='Still preparing your island…';},8000);let loaded=0;try{await Promise.all(paths.map((src,i)=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{assets[i]=img;$('#loadbar').value=++loaded;resolve();};img.onerror=()=>reject(new Error(src));img.src=src;})));clearTimeout(slow);menu();}catch{clearTimeout(slow);$('#loadnote').textContent='An island asset could not load. Please reload to try again.';const b=document.createElement('button');b.textContent='Reload';b.onclick=()=>location.reload();$('.loading').append(b);}}
savePrefs();requestAnimationFrame(frame);preload();
